updateupdate

diff --git a/usr/local/bin/arcolinux-remove-variety b/usr/local/bin/arcolinux-remove-variety
--- a/usr/local/bin/arcolinux-remove-variety
+++ b/usr/local/bin/arcolinux-remove-variety
@@ -32,36 +32,53 @@ echo "###                             REMOVING VARIETY                          
 echo "###############################################################################"
 tput sgr0
 
-# Array of packages to check
-packages=("variety" "arcolinux-variety-git" "arcolinux-variety-autostart-git")  
+echo "This script will remove variety"
+read -p "Are you sure you want to proceed? (Y/y) " response
 
-# Function to check if a package is installed
-is_package_installed() {
-    if pacman -Q "$1" &> /dev/null; then
-        echo "Package $1 is installed."
-        return 0  # Success
-    else
-        echo "Package $1 is not installed."
-        return 1  # Failure
-    fi
-}
+if [[ $response =~ ^[Yy]$ ]]; then
 
-# Iterate over each package in the array
-for package in "${packages[@]}"; do
-    if is_package_installed "$package"; then
-        echo "Removing $package..."
-        sudo pacman -Rns "$package" --noconfirm
-    else
-        echo "$package is not installed, no need to remove."
-    fi
-    echo
-    echo "########################"
-    echo "Double checking $package"
-    echo "########################"
-    echo
-    if ! is_package_installed "$package"; then
-        echo "$package is not installed!"
-    else
-        echo "$package is still installed. Check manually why not."
-    fi
-done
+    # Array of packages to check
+    packages=("variety" "arcolinux-variety-git" "arcolinux-variety-autostart-git")  
+
+    # Function to check if a package is installed
+    is_package_installed() {
+        if pacman -Q "$1" &> /dev/null; then
+            echo "Package $1 is installed."
+            return 0  # Success
+        else
+            echo "Package $1 is not installed."
+            return 1  # Failure
+        fi
+    }
+
+    # Iterate over each package in the array
+    for package in "${packages[@]}"; do
+        if is_package_installed "$package"; then
+            echo "Removing $package..."
+            sudo pacman -Rns "$package" --noconfirm
+        else
+            echo "$package is not installed, no need to remove."
+        fi
+        echo
+        echo "########################"
+        echo "Double checking $package"
+        echo "########################"
+        echo
+        if ! is_package_installed "$package"; then
+            echo "$package is not installed!"
+        else
+            echo "$package is still installed. Check manually why not."
+        fi
+    done
+
+else
+    echo "####################################"
+    echo "Operation canceled by user."
+    echo "####################################"
+
+fi
+
+echo
+echo "###############################################################################"
+echo "###                DONE - YOU CAN CLOSE THIS WINDOW                        ####"
+echo "###############################################################################"
diff --git a/usr/local/bin/toggle-chaotic-repo b/usr/local/bin/toggle-chaotic-repo
--- a/usr/local/bin/toggle-chaotic-repo
+++ b/usr/local/bin/toggle-chaotic-repo
@@ -26,47 +26,39 @@
 #tput setaf 8 = light blue
 ##################################################################################################################
 
-tput setaf 1;
-echo "###############################################################################"
-echo "###                     SCRIPT TO REMOVE REMOVE MICROCODE                  ####"
-echo "###############################################################################"
-tput sgr0
-echo "This script will remove microde packages"
-read -p "Are you sure you want to proceed? (Y/y) " response
+#[chaotic-aur]
+#SigLevel = Required DatabaseOptional
+#Include = /etc/pacman.d/chaotic-mirrorlist
 
-if [[ $response =~ ^[Yy]$ ]]; then
+# Set the file path
+FILE="/etc/pacman.conf"
 
-	if grep -q "base udev autodetect microcode" /etc/mkinitcpio.conf; then
-		echo "###############################################################################"
-		echo "Removing microcode"
-		echo "###############################################################################"
-		sudo sed -i "s/microcode //" /etc/mkinitcpio.conf;
-	fi
+# Search for "chaotic-aur" in the specified file
+if ! grep -q "chaotic-aur" "$FILE"; then
+    echo "Adding chaotic-aur repository to $FILE"
+    # Append the configuration for chaotic-aur to the file
+    {
+echo ""
+echo "#[chaotic-aur]"
+echo "#SigLevel = Required DatabaseOptional"
+echo "#Include = /etc/pacman.d/chaotic-mirrorlist"
+    } | sudo tee -a "$FILE"
+fi
 
-	echo
+if grep -q "#\[chaotic-aur\]" /etc/pacman.conf; then
 	echo "###############################################################################"
-	echo "Removing the correct microcode - intel or amd"
+	echo "Activate the chaotic repo"
 	echo "###############################################################################"
-	cpu=$(cat /proc/cpuinfo | grep vendor_id | uniq | awk '{print $3}')
-	echo "We are removing the package for this cpu: "$cpu
-	echo "###############################################################################"
-
-	if [ "$cpu" == "GenuineIntel" ]; then
-		echo "Intel CPU detected. Removing intel-ucode package..."
-		sudo pacman -R --noconfirm intel-ucode
-	elif [ "$cpu" == "AuthenticAMD" ]; then
-		echo "AMD CPU detected. Removing amd-ucode package..."
-		sudo pacman -R --noconfirm amd-ucode
-	else
-		echo "CPU type unrecognized. No microcode package removed."
-	fi
-
-	sudo mkinitcpio -P
-
+	sudo sed -i "s/#\[chaotic-aur\]/\[chaotic-aur\]/g" /etc/pacman.conf;
+	sudo sed -i "s/#SigLevel = Required DatabaseOptional/SigLevel = Required DatabaseOptional/g" /etc/pacman.conf;
+	sudo sed -i "s/#Include = \/etc\/pacman.d\/chaotic-mirrorlist/Include = \/etc\/pacman.d\/chaotic-mirrorlist/g" /etc/pacman.conf;
 else
-    echo "####################################"
-    echo "Operation canceled by user."
-    echo "####################################"
+	echo "###############################################################################"
+	echo "Deactivate the chaotic repo"
+	echo "###############################################################################"
+	sudo sed -i '0,/\[chaotic-aur\]/s/\[chaotic-aur\]/#\[chaotic-aur\]/' /etc/pacman.conf
+	sudo sed -i '/chaotic-aur/{n;s/^SigLevel = Required DatabaseOptional/#SigLevel = Required DatabaseOptional/;}' /etc/pacman.conf
+	sudo sed -i '0,/Include = \/etc\/pacman.d\/chaotic-mirrorlist/s/Include = \/etc\/pacman.d\/chaotic-mirrorlist/#Include = \/etc\/pacman.d\/chaotic-mirrorlist/' /etc/pacman.conf
 
 fi
 
